
import os
from PyQt5.QtCore import QThread, pyqtSignal
import torch
import gc
import time  # 导入 time 模块
from canvas import process_polygon_data
###-------------定义 ABorAD 推断线程-------------------
class ABorADInferenceThread(QThread):
    inferenceFinished = pyqtSignal(float, float, str, object)  # 传递AB概率、AD概率、文件路径和错误信息

    def __init__(self, model_path, file_path, parent=None):
        super().__init__(parent)
        self.model_path = model_path
        self.file_path = file_path
        self.model = None

    def run(self):
        try:
            # 加载模型
            from ultralytics import YOLO
            self.model = YOLO(self.model_path)
            print(f"Loading model: {self.model_path} from ABorADInferenceThread")

            # 执行推理
            result = self.model.predict(self.file_path, device="cpu")
            
            ab_probability = 0
            ad_probability = 0
            
            for r in result:
                probs = r.probs.data.cpu().numpy()
                ab_probability = probs[0] * 100
                ad_probability = probs[1] * 100
            
            # 发出信号，传递结果
            self.inferenceFinished.emit(ab_probability, ad_probability, self.file_path, None)
        
        except Exception as e:
            import traceback
            print(f"Error in ABorADInferenceThread: {str(e)}")
            print(traceback.format_exc())
            self.inferenceFinished.emit(0, 0, self.file_path, str(e))
        finally:
            # 释放资源
            self.model = None
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            gc.collect()


###-------------定义 YOLO 分割推断线程-------------------
class YOLOSegInferenceThread(QThread):
    inferenceFinished = pyqtSignal(object, str, object) # 定义推断完成信号
    # 该信号将传递推断结果(obj)、文件路径(str)和错误信息(obj)

    def __init__(self, model, file_path, inference_settings, parent=None):
        super().__init__(parent) 
        self.model = model
        self.file_path = file_path
        self.inference_settings = inference_settings
        self._is_interrupted = False  # 添加中断标志

    def requestInterruption(self):
        """请求中断线程执行"""
        self._is_interrupted = True

    def run(self):
        try:
            # 获取推断设置
            conf = self.inference_settings.get("conf", 0.5)
            iou = self.inference_settings.get("iou", 0.7)
            device = self.inference_settings.get("device", "cpu").lower()
            if device == "gpu":
                device = "0"  # 或者根据实际情况设置 GPU 设备编号
            save_path = self.inference_settings.get("save_path", os.path.join(os.getcwd(), "Inference_OutPut"))
            
            # 获取新增的参数
            imgsz = self.inference_settings.get("imgsz", 1024)
            max_det = self.inference_settings.get("max_det", 500)

            # 确保保存路径存在
            if not os.path.exists(save_path):
                os.makedirs(save_path)

            file_name = os.path.basename(self.file_path)

            # 收集所有要传递给 predict 方法的参数
            predict_params = {
                "source": self.file_path,
                "conf": conf,
                "iou": iou,
                "save": True,
                "save_txt": True,
                "device": device,
                "imgsz": imgsz,
                "max_det": max_det,
                "project": save_path,
                "show_conf": False,
                "show_boxes": False,
                "retina_masks": True,
                "name": file_name + " generated by StomataQuant",
            }

            # 在调用 predict 方法之前，打印出所有参数
            print("The following parameters will be passed to self.model.predict when it is about to be called:：")
            for key, value in predict_params.items():
                print(f"{key}: {value}")


            # 调用 YOLO 的 predict 方法，传入参数字典
            results = self.model.predict(**predict_params)

            self.inferenceFinished.emit(results, self.file_path, None)
        

        except Exception as e:
            import traceback
            print(f"Error in YOLOSegInferenceThread: {str(e)}")
            print(traceback.format_exc())
            self.inferenceFinished.emit(None, self.file_path, str(e))
        finally:
            # 确保在推断完成后正确释放资源
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            gc.collect()
            time.sleep(1)  # 停顿 0.5 秒


class PolygonProcessThread(QThread):
    processingFinished = pyqtSignal(dict, list, object)  # 传递处理后的多边形字典、原始形状列表、错误信息

    def __init__(self, polygons_by_class, image_width, image_height, json_obj, parent=None):
        super().__init__(parent)
        self.polygons_by_class = polygons_by_class
        self.image_width = image_width
        self.image_height = image_height
        self.json_obj = json_obj
        self._is_interrupted = False

    def requestInterruption(self):
        """请求中断线程执行"""
        self._is_interrupted = True

    def run(self):
        try:
            # 执行多边形处理
            processed_polygons = process_polygon_data(self.polygons_by_class, 
                                                     self.image_width, 
                                                     self.image_height)
            
            # 发出信号，传递处理结果
            self.processingFinished.emit(processed_polygons, self.json_obj, None)
        
        except Exception as e:
            import traceback
            print(f"Error in PolygonProcessThread: {str(e)}")
            print(traceback.format_exc())
            self.processingFinished.emit({}, self.json_obj, str(e))


###-------------定义热图生成线程-------------------
# 修改 HeatMapGenerationThread 类

class HeatMapGenerationThread(QThread):
    heatmapGenerated = pyqtSignal(str, object)  # 传递保存路径和错误信息
    
    def __init__(self, original_image, shapes, feature_name, colormap_name, output_path, original_file_name="", scale_info=None, parent=None):
        super().__init__(parent)
        self.original_image = original_image  # QImage 对象
        self.shapes = shapes  # 形状列表
        self.feature_name = feature_name  # 特征名称
        self.colormap_name = colormap_name  # 颜色映射名称
        self.output_path = output_path  # 输出路径
        self.original_file_name = original_file_name  # 添加原始文件名参数
        self.scale_info = scale_info  # 添加比例尺信息
        self._is_interrupted = False  # 添加中断标志
    
    def requestInterruption(self):
        """请求中断线程执行"""
        self._is_interrupted = True    

    def run(self):
        try:
            if self._is_interrupted:
                self.heatmapGenerated.emit("", "Operation canceled")
                return
            # 导入必要的库
            import matplotlib
            matplotlib.use('Agg')  # 使用非交互式后端
            import matplotlib.pyplot as plt
            from matplotlib.colors import Normalize
            import numpy as np
            import tempfile
            import os
            from PyQt5.QtGui import QImage, QPainter, QPolygonF, QPen, QBrush, QColor, QPixmap
            from PyQt5.QtCore import Qt, QDateTime
            
            # 创建临时文件用于颜色条
            fd, temp_colorbar = tempfile.mkstemp(suffix='.png')
            os.close(fd)
            
            # 确保输出目录存在
            if not os.path.exists(self.output_path):
                os.makedirs(self.output_path)
            
            # 创建透明图层用于热图
            heatmap_image = QImage(self.original_image.size(), QImage.Format_ARGB32)
            heatmap_image.fill(Qt.transparent)
            
            # 提取特征值
            feature_values = []
            
            # 检查是否需要应用比例尺
            needs_scale = self.feature_name in ["Area", "Perimeter", "MER Length", "MER Width"]
            scale_factor = 1.0
            unit_text = "pixel"
            
            if needs_scale and self.scale_info:
                scale_factor = self.scale_info.get('scale', 1.0)
                unit_text = self.scale_info.get('unit', 'pixel')
            
            for shape in self.shapes:
                if (hasattr(shape, 'feature_results') and 
                    isinstance(shape.feature_results, dict) and 
                    self.feature_name in shape.feature_results):
                    value = shape.feature_results[self.feature_name]
                    if isinstance(value, (int, float)):
                        feature_values.append(value)
            
            if not feature_values:
                self.heatmapGenerated.emit("", f"没有找到特征: {self.feature_name}")
                return
            
            # 标准化特征值 (0 到 1)
            min_value = min(feature_values)
            max_value = max(feature_values)
            value_range = max_value - min_value if max_value > min_value else 1.0
            
            # 获取颜色映射
            cmap = plt.get_cmap(self.colormap_name)
            
            # 创建热图绘制器
            painter = QPainter()
            painter.begin(heatmap_image)
            painter.setRenderHint(QPainter.Antialiasing)
                        
            # 在for循环中的计算颜色部分
            for shape in self.shapes:
                if (not hasattr(shape, 'feature_results') or 
                    not isinstance(shape.feature_results, dict) or 
                    self.feature_name not in shape.feature_results):
                    continue
                
                value = shape.feature_results[self.feature_name]
                if not isinstance(value, (int, float)):
                    continue
                
                # 计算颜色 - 修改这部分代码
                if value >= max_value:  # 直接判断是否为最大值
                    normalized_value = 0.999

                elif value <= min_value:  # 直接判断是否为最小值
                    normalized_value = 0.001
        
                else:
                    normalized_value = (value - min_value) / value_range if value_range else 0.5
                
                normalized_value = max(0, min(1, normalized_value))  # 确保在 [0,1] 范围内
                rgba = cmap(normalized_value)
                color = QColor(
                    int(rgba[0] * 255), 
                    int(rgba[1] * 255), 
                    int(rgba[2] * 255), 
                    180  # Alpha透明度
                )
                
                # 绘制多边形
                if shape.shape_type == 'polygon' and len(shape.pointslist) > 2:
                    polygon = QPolygonF(shape.pointslist)
                    painter.setPen(QPen(color, 2))
                    painter.setBrush(QBrush(color))
                    painter.drawPolygon(polygon)
            
            painter.end()
            
            # 创建结果图像
            result_image = QImage(self.original_image.size(), QImage.Format_RGB32)
            result_painter = QPainter()
            result_painter.begin(result_image)
            result_painter.drawImage(0, 0, self.original_image)
            result_painter.drawImage(0, 0, heatmap_image)
            result_painter.end()
            
            # 创建颜色条
            plt.close('all')  # 确保关闭之前的图形
            fig, ax = plt.subplots(figsize=(6, 0.6))
            fig.subplots_adjust(bottom=0.5)
            norm = Normalize(min_value, max_value)
            cb = plt.colorbar(plt.cm.ScalarMappable(norm=norm, cmap=cmap), 
                            cax=ax, orientation='horizontal')
            
            # 为颜色条添加适当的单位
            if needs_scale and self.scale_info:
                # 为不同特征类型添加适当的单位标签
                if self.feature_name == "Area":
                    cb.set_label(f'{self.feature_name} ({unit_text}²)')
                elif self.feature_name in ["Perimeter", "MER Length", "MER Width"]:
                    cb.set_label(f'{self.feature_name} ({unit_text})')
            else:
                cb.set_label(f'{self.feature_name}')
                
            fig.savefig(temp_colorbar, bbox_inches='tight', dpi=100)
            plt.close(fig)
            
            # 加载颜色条图像
            colorbar_image = QImage(temp_colorbar)
            
            # 创建最终图像
            final_height = result_image.height() + colorbar_image.height() + 10
            final_image = QImage(result_image.width(), final_height, QImage.Format_RGB32)
            final_image.fill(QColor(255, 255, 255))
            
            # 绘制到最终图像
            final_painter = QPainter()
            final_painter.begin(final_image)
            final_painter.drawImage(0, 0, result_image)
            
            # 在底部绘制颜色条
            scaled_colorbar = colorbar_image.scaled(
                result_image.width() - 20, 
                colorbar_image.height(),
                Qt.KeepAspectRatio, 
                Qt.SmoothTransformation
            )
            final_painter.drawImage(
                (final_image.width() - scaled_colorbar.width()) // 2,
                result_image.height() + 5, 
                scaled_colorbar
            )
            final_painter.end()
            
            # 保存结果
            # 保存结果
            # 保存结果
            # 保存结果
            if self.original_file_name:
                # 提取文件名（不包含路径和扩展名）
                base_name = os.path.basename(self.original_file_name)
                file_name_without_ext = os.path.splitext(base_name)[0]
                file_name = f"{self.feature_name}_{file_name_without_ext}.png"
            else:
                # 如果没有原始文件名，使用时间戳作为后备方案
                file_name = f"{self.feature_name}_{QDateTime.currentDateTime().toString('yyyyMMdd_hhmmss')}.png"
            
            # 构建完整的文件保存路径
            file_path = os.path.join(self.output_path, file_name)
            
            # 保存图像
            if final_image.save(file_path):
                self.heatmapGenerated.emit(file_path, None)
            else:
                self.heatmapGenerated.emit("", "Failed to save heatmap image.")

                
            # 清理临时文件
            try:
                if os.path.exists(temp_colorbar):
                    os.remove(temp_colorbar)
            except:
                pass
                
        except Exception as e:
            import traceback
            print(f"Error generating Heat Map: {str(e)}")
            print(traceback.format_exc())
            self.heatmapGenerated.emit("", str(e))